version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: kingsatm
      POSTGRES_USER: client
      POSTGRES_PASSWORD: client

    expose:
      - 5432

  kingsatm:
    depends_on:
      - db
    restart: unless-stopped
    build: .
    ports:
      - 8090:7000

    command: gradle bootRun --stacktrace --args="--spring.datasource.url=jdbc:postgresql://db:5432/kingsatm"
    